spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=${PORT:8080}


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


payu.key=${PAYU_KEY}
payu.salt=${PAYU_SALT}
payu.url=${PAYU_URL}


groq.api.key=${GROQ_API_KEY}
groq.api.url=${GROQ_API_URL}


twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}
twilio.enabled=${TWILIO_ENABLED}


fast2sms.api.key=${FAST2SMS_API_KEY}
fast2sms.enabled=${FAST2SMS_ENABLED}


spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE}

otp.expiry.minutes=${OTP_EXPIRY_MINUTES}


datagov.api.key=${DATAGOV_API_KEY}